**TASK:** import numpy

In [2]:
import numpy as np

**TASK:** define vector 'x' with three coordinates

In [22]:
X = np.array([1,2,3])
X

array([1, 2, 3])

**TASK:** define (2 x 2) matrix 'A' 


In [20]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

**TASK:** define (2 x 2) matrix 'B'

In [21]:
B = np.array([[2,2],[6,4]])
B 

array([[2, 2],
       [6, 4]])

**TASK:** check the type of 'x'

In [23]:
type(X)

numpy.ndarray

**TASK:** check the type of 'A'

In [14]:
type(A)

numpy.ndarray

**TASK:**  check the shape of 'x'


In [15]:
X.shape

(3,)

**TASK:** check the type of 'A'

In [16]:
A.shape

(2, 2)

**TASK:** 

In [17]:
"""
Define function 'have_same_shape' which checks if two arrays have same shape.

PARAMS:
    array_1 (numpy.ndarray) - first array
    array_2 (numpy.ndarray) - second array
RETURN:
    True - if arrays have same shape
    False - if arrays do not have same shape

Also print 'Arrays must have same shape!' when returning False
"""

"\nDefine function 'have_same_shape' which checks if two arrays have same shape.\n\nPARAMS:\n    array_1 (numpy.ndarray) - first array\n    array_2 (numpy.ndarray) - second array\nRETURN:\n    True - if arrays have same shape\n    False - if arrays do not have same shape\n\nAlso print 'Arrays must have same shape!' when returning False\n"

In [25]:
array_1 = np.array([[2,2],[5,7]])
array_2 = np.array([[1,0],[4,4]])
def have_same_shape(array_1,array_2):
    if array_1.shape == array_2.shape:
        return True
    else:
        return False,"Arrays must have same shape!"
    
have_same_shape(array_1,array_2)

True

**TASK:** call the function 'have_same_shape' with matrix 'A' and vector 'x' as inputs

In [19]:
have_same_shape(A,X)

(False, 'Arrays must have same shape!')

**TASK:**  call the function 'have_same_shape' with matrix 'A' and matrix 'B' as inputs

In [20]:
have_same_shape(A,B)

True

**TASK:** 

In [21]:
"""
Define function 'matrix_addition' which perform matrix addition value by value.

PARAMS:
    A (numpy.ndarray) - first array
    B (numpy.ndarray) - second array
RETURN:
    C (numpy.ndarray) - new A+B array

In this task do not consider broadcasting.
Do not forget to check arrays shapes (you can use 'have_same_shape' function defined before)

"""


"\nDefine function 'matrix_addition' which perform matrix addition value by value.\n\nPARAMS:\n    A (numpy.ndarray) - first array\n    B (numpy.ndarray) - second array\nRETURN:\n    C (numpy.ndarray) - new A+B array\n\nIn this task do not consider broadcasting.\nDo not forget to check arrays shapes (you can use 'have_same_shape' function defined before)\n\n"

In [26]:
def matrix_addition(A,B):
    A = np.array([[3,3],[2,4]])
    B = np.array([[1,6],[3,3]])
    C = A + B 
    return C
print(matrix_addition(A,B))
have_same_shape(A,B)

[[4 9]
 [5 7]]


True

**TASK:** call the function 'matrix_addition' with matrix 'A' and matrix 'B' as inputs

In [31]:
matrix_addition(A,B)

array([[4, 9],
       [5, 7]])

**TASK:** 

In [28]:
"""
Define 'multiple_matrix_adition' function that takes list of arrays as the input and perform array addition

PARAMS:
   lst_of_arr (list) - list of numpy.ndarrays
RETURN:
    NEW_ARRAY (numpy.ndarray) - new array

Use 'matrix_addition' function defined before.
"""

"\nDefine 'multiple_matrix_adition' function that takes list of arrays as the input and perform array addition\n\nPARAMS:\n   lst_of_arr (list) - list of numpy.ndarrays\nRETURN:\n    NEW_ARRAY (numpy.ndarray) - new array\n\nUse 'matrix_addition' function defined before.\n"

In [38]:
import numpy as np

lst_of_arr = np.array([A,A,B,B,B])
def multiple_matrix_addition(lst_of_arr):
    NEW_ARRAY = np.zeros(lst_of_arr[0].shape)
    for i in lst_of_arr:
        NEW_ARRAY += i
        print(NEW_ARRAY)
        
multiple_matrix_addition(lst_of_arr)

[[1. 2.]
 [3. 4.]]
[[2. 4.]
 [6. 8.]]
[[ 4.  6.]
 [12. 12.]]
[[ 6.  8.]
 [18. 16.]]
[[ 8. 10.]
 [24. 20.]]


**TASK:** call the function 'multiple_matrix_addition' with matrix [A,A,B,B,B] as input


In [39]:
multiple_matrix_addition([A,A,B,B,B])

[[1. 2.]
 [3. 4.]]
[[2. 4.]
 [6. 8.]]
[[ 4.  6.]
 [12. 12.]]
[[ 6.  8.]
 [18. 16.]]
[[ 8. 10.]
 [24. 20.]]


**TASK:** 

In [ ]:
"""
Define function 'can_multiply' that checks if two arrays (matrices) can be multiplied

PARAMS: 
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    True - if arrays can be multiplied, also print the shape of the new array
    False - if arrays can not be multiplied, also print 'Matrices can not be multiplied.'
    
"""

In [41]:
import numpy as np
array_a = np.array([[3,3],[2,4],[1,1]])
array_b = np.array([[3,1],[3,4]])

def can_multiply(array_a,array_b):
    if array_a.shape[1]!=array_b.shape[0]:
        print("Matrices can not be multiplied.")
        return False
    else:
        
        array_c = np.dot(array_a,array_b)
        print(array_c.shape)
        return True
        
    
can_multiply(array_a,array_b)

(3, 2)


True

**TASK:** call the function 'can_multiply' with matrix 'A' and 'B' as inputs

In [48]:
can_multiply(A,B)

True

**TASK:**  define matrix (3 x 2) matrix C

In [47]:
C = np.array([[1,2],[3,4],[4,5]])
C

array([[1, 2],
       [3, 4],
       [4, 5]])

**TASK:**  call the function 'can_multiply' with matrix 'A' and 'C' as inputs

In [46]:
can_multiply(A,C)

(False, 'Matrices can not be multiplied')

**TASK:**  call the function 'can_multiply' with matrix 'C' and 'A' as inputs (now C,A not A,C). Do you know why is the result different?

In [45]:
can_multiply(C,A)

True

Yes because columns of matrix C are not equal to rows of matrix A
i.e. AC != to CA, matrix multiplication is not commutative

**TASK:** 

In [ ]:
"""
Define function 'matrix_multiplication' that multiply two numpy.ndarrays

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    NEW_ARRAY (numpy.ndarray) - new A * B array
    
Do not forget to check if two matrices can be multiplied.

"""

In [26]:
def matrix_multiplication(array_a,array_b):
    NEW_ARRAY = np.dot(array_a,array_b)
    return NEW_ARRAY
if can_multiply(array_a,array_b)== True:
    print(matrix_multiplication(array_a,array_b))
else:
    print(can_multiply(array_a,array_b))


[[18 15]
 [18 18]
 [ 6  5]]


**TASK:**  call the function 'matrix_multiplication' with matrix 'C' and 'B' 


In [ ]:
matrix_multiplication(C,B)

**TASK:** call the function 'matrix_multiplication' with matrix 'A' and 'C' 

In [ ]:
matrix_multiplication(A,C)